http302/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url('admin/', admin.site.urls),
    url('', include('urlshortener.urls'))
]

urlshortener/urls.py
from django.conf.urls import url

from . import views

app_name = "urlshortener"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^shrink$', views.shrink, name="shrink"),
    url(r'^shorturl/([0-9a-zA-Z-_]+)$', views.result, name="result"),
    url(r'qr', views.qr, name='qr'),
    url(r'([0-9a-zA-Z-_]+)', views._redirect, name="redirect")
]

urlshortener/models.py
from django.db import models

class Url(models.Model):
    code = models.CharField(primary_key=True, max_length=10)
    url = models.URLField()
    created_at = models.DateTimeField(auto_now=True)

urlshortener/views.py
import random, hashlib, re
import boto3, botocore
import qrcode

from datetime import datetime

from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse

from .models import Url

def index(request):
    return render(request, 'urlshortener/index.html')

def _redirect(request, id):
    dynamo = boto3.resource('dynamodb', region_name="us-east-1")
    table = dynamo.Table('urls')

    url = table.query(
        IndexName = "code-index",
        KeyConditionExpression = "code = :code",
        ExpressionAttributeValues = { ':code': id },
    )

    try:
        return redirect(url['Items'][0]['url'])
    except IndexError:
        raise Http404()

def shrink(request):
    url = request.POST['url']

    if not re.match(r'^(http|https)', url, re.I):
        url = f"http://{url}"

    hash = hashlib.sha1(url.encode()).hexdigest()
    date = datetime.today()
    code = randomString()

    dynamo = boto3.resource('dynamodb', region_name="us-east-1")
    table = dynamo.Table('urls')

    try:
        table.put_item(Item= dict(
            username='null',
            hash=hash,
            code=code,
            url = url,
            created=date.isoformat()
            ),
            ConditionExpression="attribute_not_exists(#hash)",
            ExpressionAttributeNames={'#hash': 'hash'}
        )
    except botocore.exceptions.ClientError:
        url2 = table.get_item(Key=dict(
            username='null',
            hash=hash
        ))

        code = url2['Item']['code']

    result_url = reverse('urlshortener:result', args=[code])
    return redirect(result_url)

def result(request, code):
    return render(request, 'urlshortener/result.html', dict(
        url = f'http://r302.co/{code}'
    ))

def randomString():
    chars = 'abcdefghjkmnpqrstuvwxyz23456789'
    string = ''

    for _ in range(0,5):
        string += random.choice(chars)
    return string

def qr(request):
    qr = qrcode.make(request.GET['url'])
    response = HttpResponse(content_type="image/png")
    qr.save(response, 'PNG')
    return response

    # return render(request, 'urlshortener/test.html')

urlshortener/templates/urlshortener/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

        <meta name="description" content="Acortador de URL simple, rápido y fácil.">
        <meta name="keywords" content="Acortador de URL, Encogedor de URL, URL shortening, URL Shortener">
        <meta name="author" content="Mario Juárez">
        <title>r302</title>

        <script src="http://cdn.jsdelivr.net/vue/1.0.24/vue.min.js" charset="utf-8"></script>
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    </head>
    <body>
        <div class="container" id="app">
            {% block content %}{% endblock %}
        </div>

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-2811783-10', 'auto');
        ga('send', 'pageview');
    </script>
    </body>
</html>

urlshortener/templates/urlshortener/index.html
{% extends 'urlshortener/base.html' %}

{% block content %}
    <div class="col-sm-8 col-sm-offset-2">
        <h1>Acortador de URL<small> simple, rápido y fácil</small></h1>

        <form action="{% url 'urlshortener:shrink' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="url">Ingresa la URL que quieras acortar:</label>
                <input v-model="url" class="form-control" type="text" name="url" value="" id="url" placeholder="http://example.com/articulo/123">
            </div>

            <div class="">
                <button type="submit" class="btn btn-block btn-primary" :class="{'disabled': isEmpty}">
                    Acortar
                </button>
            </div>
        </form>
    </div>


    <script type="text/javascript">
        vm = new Vue({
            el: '#app',
            data: {},
            computed: {
                isEmpty: function(){
                    return this.url.length < 5
                },
            },
        })
    </script>

{% endblock %}

urlshortener/templates/urlshortener/result.html
{% extends 'urlshortener/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <h1>URL Corta:</h1>
            <form class="" action="index.html" method="post">
                <input class="form-control" type="text" name="name" value="{{url}}" readonly="readonly">
            </form>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <a href="{% url 'urlshortener:index' %}">Regresar y acortar otra URL</a>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text-center">
            <img class="responsive" src="{% url 'urlshortener:qr' %}?url={{url|urlencode}}" alt="" />
        </div>
    </div>
{% endblock %}

urlshortener/templates/urlshortener/test.html
{% extends 'urlshortener/base.html' %}

{% block content %}
    <template id="contador">
        <button class="btn btn-primary" type="button" name="button" @click="increment">
            Contador {% verbatim %} {{text}} {{counter}}{% endverbatim %}
        </button>
    </template>

    <div class="row">
        <form class="" action="index.html" method="post" @submit.prevent="handle">
            <contador text="hola"></contador>
            <contador text="hello"></contador>
        </form>
    </div>

    <script type="text/javascript">
        vm = new Vue({
            el: '#app',
            data: {
            },
            methods: {

                handle: function(e){
                    // alert('hi')
                }
            },
            components: {
                contador: {
                    template: '#contador',
                    props: ['text'],
                    data: function(){
                        return {
                            counter: 1
                        }
                    },
                    methods: {
                        increment: function(){
                            this.counter += 1
                        },
                    }
                }
            }
        })
    </script>

{% endblock %}